let data = [
  {
    id: 1,
    title: 'Learn Wedding Photography',
    description: 'Learn wedding photography',
    price: 50,
    currency: 'USD',
    coverImg: 'wedding-photography.png',
    stats: {
      rating: 5.0,
      reviewCount: 23,
      eventUnit: 'Session',
    },
    location: 'Online',
    openSpot: 0,
  },
  {
    id: 2,
    title: 'Camping',
    description: 'Experience the wildlife',
    price: 60,
    currency: 'USD',
    coverImg: 'camping.png',
    stats: {
      rating: 4.6,
      reviewCount: 6,
      eventUnit: 'Night',
    },
    location: 'USA',
    openSpot: 20,
  },
  {
    id: 3,
    title: 'Build a bike',
    description: 'Build a bike to explore the city',
    price: 200,
    currency: 'USD',
    coverImg: 'bicycle-experience.png',
    stats: {
      rating: 4.9,
      reviewCount: 60,
      eventUnit: 'Session',
    },
    location: 'Detroit',
    openSpot: 3,
  },
  {
    id: 4,
    title: 'Cooking Laboratory',
    description: 'Learn how to cook with us',
    price: 75,
    currency: 'USD',
    coverImg: 'cooking-lab.png',
    stats: {
      rating: 4.0,
      reviewCount: 20,
      eventUnit: 'Class',
    },
    location: 'Online',
    openSpot: 2,
  },
  {
    id: 5,
    title: '爬象山',
    description: '＊ 教練帶你爬象山 *',
    price: 500,
    currency: 'NTD',
    coverImg: 'elephant-mountain.png',
    stats: {
      rating: 5.0,
      reviewCount: 15,
      eventUnit: 'Class',
    },
    location: '台北。台灣',
    openSpot: 5,
  },
]
export default data